name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clone repository to web root
        run: |
          cd /var/www/html/
          sudo rm -rf *
          sudo git clone https://github.com/ncd282005/backend-docker.git 
      - name: Verify deployment
        run: |
          ls -la /var/www/html
          pm2 start index.js
        

